Repository zsa/qmk_firmware, pull requests merged in 2019-06, with the labels that each got.

#58 Add Solus OS support to Linux install scripts
  changelog.md
  util/linux_install.sh
Labels: enhancement

#59 Fix up Debouncing in AVR Templates
  changelog.md
  quantum/template/avr/config.h
  quantum/template/ps2avrgb/config.h
Labels: enhancement

#62 Fix TO() and DF() calling layer_state_set_[kb,user] twice (qmk#6003)
  changelog.md
  tmk_core/common/action.c
Labels: bug, enhancement

#63 Fixing matrix_scan so it properly returns changed status
  changelog.md
  quantum/matrix.c
Labels: enhancement

#64 Add belgian layout for sendstring (qmk#6008)
  changelog.md
  quantum/keymap_extras/sendstring_belgian.h
Labels: enhancement

#65 Fixing matrix_scan so it properly returns changed status on Ergodox EZ
  keyboards/ergodox_ez/matrix.c
Labels: enhancement

#67 Smallish overhaul of Auto-Shift feature
  changelog.md
  quantum/process_keycode/process_auto_shift.c
  quantum/process_keycode/process_auto_shift.h
Labels: bug, enhancement

#68 upgrade gcc-arm-none-eabi from the default 5.4.1 to 6.3.1
  Dockerfile
  changelog.md
Labels: enhancement

#69 Moving rgb typedefs into a single location (#5978)
  changelog.md
  drivers/avr/apa102.h
  drivers/avr/ws2812.h
  quantum/color.h
  quantum/rgblight.h
  quantum/rgblight_types.h
Labels: enhancement

#70 Fixes compile errors for ATSAM ARM keyboards
  changelog.md
  tmk_core/protocol/arm_atsam/md_bootloader.h
Labels: bug

#71 Parameterise STM32 I2C pin modes and timing parameters. (#5671)
  changelog.md
  drivers/arm/i2c_master.c
  drivers/arm/i2c_master.h
Labels: enhancement

#72 Add additional pins for Teensy 3.x and LC
  changelog.md
  quantum/config_common.h
Labels: enhancement

#73 Fix debouncing issue for eager algorithms
  changelog.md
  quantum/debounce/eager_pk.c
  quantum/debounce/eager_pr.c
Labels: enhancement

#74 Planck Ez disable leds
  keyboards/planck/ez/ez.c
  keyboards/planck/keymaps/default/rules.mk
  keyboards/planck/keymaps/glow/config.h
  keyboards/planck/keymaps/glow/keymap.c
  keyboards/planck/keymaps/glow/readme.md
  keyboards/planck/keymaps/glow/rules.mk
Labels: enhancement

#75 Fixing OLED Driver for 128x64 displays
  drivers/oled/oled_driver.c
  drivers/oled/oled_driver.h
Labels: bug, enhancement

#76 Add SH1106 OLED support
  drivers/oled/oled_driver.c
  drivers/oled/oled_driver.h
Labels: enhancement

#77 Copy avr teensy flash logic to arm (#6016)
  tmk_core/chibios.mk
Labels: enhancement

#78 Change from avr-gcc@7 to 8 for Mac
  util/macos_install.sh
Labels: enhancement

#82 Enable RGB Matrix Sleep functionality
  keyboards/ergodox_ez/ergodox_ez.c
  keyboards/planck/ez/ez.c
Labels: bug

#79 Planck: Layout Macro Refactor (#4402)
  keyboards/planck/ez/ez.h
  keyboards/planck/ez/info.json
  keyboards/planck/ez/readme.md
  keyboards/planck/planck.h
  keyboards/planck/readme.md
Labels: bug, enhancement

#83 Fix compilation error when I2C and encoder is enabled for split code
  quantum/split_common/transport.c
Labels: bug

#84 Compilation error when importing abnt2 extra keymap
  quantum/keymap_extras/keymap_br_abnt2.h
Labels: bug
